### ISSUE TITLE
famous imgurian feature

### ISSUE THREAD

**Issue by from-nibly** [from-nibly/imgur-heart#20]
be able highlight famous imgurians and what they are famous for.  we will need to create a json structure to store this data and a consistent framework for displaying different kinds of content.

**Comment by s-thom** [comment]
I'll start working on this next time I sit in front of a computer. 

What kind of highlighting are you thinking? Change color of name? Add a piece of text behind them (same style to "OP is a ___")? Should there be something to highlight contributors to this repo?

**Comment by from-nibly** [comment]
I think we are going to have pre-canned content on a static json serving server. we want to be able to show a chat bubble off to the left of the users name that shows what they are famous for. or something like that.  but first i need to start integrating tests into the plugin.

**Comment by anton-christensen** [comment]
I'm working with imgurians to compile a list. Just leave this one for me
