### ISSUE TITLE
sera pls

### ISSUE THREAD

**Issue by from-nibly** [from-nibly/imgur-heart#3]
Make the spinning icon customizable

**Comment by anton-christensen** [comment]
Objection! current one is awsome - http://imgur.com/gallery/pKopwXp

**Comment by clementallen** [comment]
Agreed, why fix it if it ain't broke?

**Comment by from-nibly** [comment]
it is awesome! but i think it would be fun to be able to change it.  I mean this is really just for kicks and giggles anyway.
