### ISSUE TITLE
OP is a _____

### ISSUE THREAD

**Issue by from-nibly** [from-nibly/imgur-heart#4]
change all the OP labels to pink ____ labels (or whatever else you want)

**Comment by jazware** [comment]
Ehhhhhh I think that's taking it a bit too far...

**Comment by s-thom** [comment]
Fixed in #14.

**Comment by from-nibly** [comment]
agreed.  We could change it to op is a ____ or whatever

**Comment by s-thom** [comment]
Added more commits to the branch. Now with more customization!
